require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.2
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "spec/rails_helper.rb"
    - "config/initializers/*"
    - "config/application.rb"
    - "config/environments/development.rb"
  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods:
    ["describe", "context", "feature", "scenario", "let", "it", "draw"]

Metrics/ParameterLists:
  Max: 6
