version: "3"

services:
  web:
    build: .
    container_name: free_lancers_tech
    command: "bin/setup"
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    tty: true
    env_file: .env.development
    depends_on:
      - db
      - cache

  jobs:
    build: .
    container_name: sidekiq
    command: "bin/setup_sidekiq"
    volumes:
      - .:/opt/app
    env_file: .env.development
    depends_on:
      - db
      - cache

  db:
    image: postgres:13-alpine
    container_name: postgresql
    env_file: .env.database
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  cache:
    image: redis
    container_name: redis
    command: "redis-server"
