version: "3"

services:
  web:
    build: .
    command: "bin/setup"
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DOCKER_COMPOSE_SESSION: true
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
