default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: freelancers_tech_development

test:
  <<: *default
  database: freelancers_tech_test
production:
  <<: *default
  database: freelancers_tech_production
  username: freelancers_tech
  password: <%= ENV['FREELANCERS_TECH_DATABASE_PASSWORD'] %>
